export const FETCH_BEANS = "FETCH_BEANS";
export const FETCH_CATALOG_LIST = "FETCH_CATALOG_LIST";
export const FETCH_DISTRIBUTOR_LIST = "FETCH_DISTRIBUTOR_LIST";
export const DISTRIBUTOR_REGISTER = "DISTRIBUTOR_REGISTER";
export const UPDATE_DISTRIBUTOR = "UPDATE_DISTRIBUTOR";
export const UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT";
